"""
Interactive script to help set up your .env file with API keys.
"""

import os
from pathlib import Path

def setup_env_file():
    """Interactive setup for .env file."""
    print("🔑 Setting up your API keys...")
    print("This script will help you create a .env file with your API keys.\n")
    
    # Check if .env already exists
    env_path = Path(".env")
    if env_path.exists():
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/n): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    # Collect API keys
    print("Please enter your API keys (press Enter to skip optional ones):\n")
    
    openai_key = input("🤖 OpenAI API Key (required): ").strip()
    if not openai_key:
        print("❌ OpenAI API key is required. Exiting...")
        return
    
    anthropic_key = input("🧠 Anthropic API Key (required): ").strip()
    if not anthropic_key:
        print("❌ Anthropic API key is required. Exiting...")
        return
    
    google_key = input("🔍 Google Gemini API Key (required): ").strip()
    if not google_key:
        print("❌ Google API key is required. Exiting...")
        return
    
    # Optional keys
    print("\n📋 Optional API keys (for advanced features):")
    elevenlabs_key = input("🎵 ElevenLabs API Key (optional): ").strip()
    azure_speech_key = input("🗣️  Azure Speech Key (optional): ").strip()
    azure_region = input("🌍 Azure Speech Region (optional): ").strip()
    stability_key = input("🎨 Stability AI Key (optional): ").strip()
    
    # Create .env content
    env_content = f"""# Automated Story Engine API Keys
# Generated by setup script

# Required API Keys
OPENAI_API_KEY={openai_key}
ANTHROPIC_API_KEY={anthropic_key}
GOOGLE_API_KEY={google_key}

# Optional API Keys
"""
    
    if elevenlabs_key:
        env_content += f"ELEVENLABS_API_KEY={elevenlabs_key}\n"
    else:
        env_content += "# ELEVENLABS_API_KEY=your_elevenlabs_api_key_here\n"
    
    if azure_speech_key:
        env_content += f"AZURE_SPEECH_KEY={azure_speech_key}\n"
    else:
        env_content += "# AZURE_SPEECH_KEY=your_azure_speech_key_here\n"
        
    if azure_region:
        env_content += f"AZURE_SPEECH_REGION={azure_region}\n"
    else:
        env_content += "# AZURE_SPEECH_REGION=your_azure_region_here\n"
    
    if stability_key:
        env_content += f"STABILITY_API_KEY={stability_key}\n"
    else:
        env_content += "# STABILITY_API_KEY=your_stability_api_key_here\n"
    
    env_content += """
# System Settings
ENVIRONMENT=development
DEBUG=true
"""
    
    # Write the file
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully!")
        print(f"📍 Location: {env_path.absolute()}")
        print("\n🚀 You're ready to run the Story Engine!")
        print("Try running: python demo.py")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    setup_env_file()
